name: sword_result
description: Result type and helpers for SwordStack.
version: 0.1.0
repository: https://github.com/mattramostech/sword-stack
issue_tracker: https://github.com/mattramostech/sword-stack/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
